### PR TITLE
CON-2568 part 2: Remove support for node 14

### PR DESCRIPTION
**Pull request by camillecroci**
# what is this about

[Jira ticket](https://financialtimes.atlassian.net/browse/CON-2562): 
we are updating some stuff everywhere following this [migration guide](https://docs.google.com/document/d/1BkXL-DQ4Mni_WtMGiwhWyXAChNCYR1Wav26ogcE0oJw/edit#heading=h.nc8rr6a11gem). This package only needed those 2 updates: 
- Removing n-logger (done)
- **Dropping support to node 14 (what we're doing here)**

# What did I do ? 

- Remove '14' from the node engine
- Remove node 14 from the test matrix on circle ci 

# How did I test

- I ran the unit tests `make unit-test`
- Npm linked **n-lists-client** to **next-stream-page** and made sure that I was using a route that calls n-lists-client and that nothing broke. It seemed fine.

### CODE REVIEW

**Comment by gyss** [comment]
should you remove the node version here? https://github.com/Financial-Times/n-lists-client/blob/2be1a0574d449a6eb2a558868b5e9bb9cffa5adb/.circleci/config.yml#L142

**Comment by gyss** [comment]
Should all the users of this lib use node 16 or higher?

**Comment by camillecroci** [comment]
@gyss , very good question for the circle ci config. I have no idea. 
For the 2nd question, we are removing the support for node 14 everywhere, starting with the library / package 
So our repos are going to drop support to node 14 as well, and get the updated release of all our packages that got this change. This one is used by next-stream-page, so at some point in the near future, next-stream-page will have the node 14 removed from its engine and also use the new release from n-lists-client that I will create once this pr is merged
For the other apps outside content disco... well they can do it when they want

**Comment by gyss** [comment]
Regarding the CI config question, it seems those lines

```
node-version: [ "16.14", "14.19" ]
```

is what makes the CI to run the task for each of the node versions listed. That's why you can see it's still testing node 14.19 
Screenshot 2023-06-12 at 15 52 26

Looks like if you want to completely remove 14.19 you should remove that line or leave just node 16

**Comment by camillecroci** [comment]
@gyss I have removed the node 14 in the test matrix. thank you for pointing that !

**Review by gyss — APPROVED** [review]

**Comment by gyss** [comment]
Approved. I guess that the whole `matrix` section can be removed though. Maybe we need them back for the future node18 migration? (even though that'll happen only for apps?)

**Comment by camillecroci** [comment]
@gyss I assume we will need it very soon (there will be node 18 but also node 20) so I will keep it like that for now

**Pull request merged**
